name: wplab
recipe: wordpress
config:
  webroot: wordpress
  php: '7.4'
  via: 'nginx'
  database: mariadb
  xdebug: true
env_file:
  - .env
proxy:
  appserver_nginx:
    - wplab.lndo.site
  mailhog:
    - mail.wplab.lndo.site
  pma:
    - pma.wplab.lndo.site
services:
  appserver:
    type: php
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
  node:
    type: node:16
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
tooling:
  npm:
    service: node
  npx:
    service: node
  test:
    service: appserver
    cmd: "php /app/vendor/bin/phpunit -c /app/phpunit.xml"
    description: Run PHPUnit tests on a specific file or Drupal module.